import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>My Page Title</title>
        <link
          rel="preload"
          as="font"
          type="font/woff2"
          href="https://assets.revolut.com/assets/fonts/AeonikPro-Black.woff2"
          crossOrigin="anonymous"
          data-next-head=""
        />
        <link
          rel="preload"
          as="font"
          type="font/woff2"
          href="https://assets.revolut.com/assets/fonts/AeonikPro-Medium.woff2"
          crossOrigin="anonymous"
          data-next-head=""
        />
        <link
          rel="preload"
          as="font"
          type="font/woff2"
          href="https://assets.revolut.com/assets/fonts/AeonikPro-Regular.woff2"
          crossOrigin="anonymous"
          data-next-head=""
        />
        <link
          rel="preload"
          as="font"
          type="font/woff2"
          href="https://assets.revolut.com/assets/fonts/AeonikPro-Black-Capitalised.woff2"
          crossOrigin="anonymous"
          data-next-head=""
        />
        <link
          rel="preload"
          as="font"
          type="font/woff2"
          href="https://assets.revolut.com/assets/fonts/Inter-Regular.woff2"
          crossOrigin="anonymous"
          data-next-head=""
        />
        <link
          rel="preload"
          as="font"
          type="font/woff2"
          href="https://assets.revolut.com/assets/fonts/Inter-Medium.woff2"
          crossOrigin="anonymous"
          data-next-head=""
        />
        <link
          rel="preload"
          as="font"
          type="font/woff2"
          href="https://assets.revolut.com/assets/fonts/Inter-SemiBold.woff2"
          crossOrigin="anonymous"
          data-next-head=""
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
